import { ReduxProvider } from '#/redux/provider'
// import { Inter } from 'next/font/google'
import { AntdProvider } from './AntdProvider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// margin:0;background-color: hsla(0,0%,0%,.9);
export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, backgroundColor: 'hsla(0,0%,0%,.9)' }}>
        <ReduxProvider>
          <AntdProvider>{props.children}</AntdProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
