/**
 * <p>
 * 商品
 * </p>
 *
 * @version: v1.0
 * @author: Clover
 * @create: 2023-07-18 13:04
 */
import type { FC } from 'react'
import ActionBar from './ActionBar'
import ProductGrid from './ProductGrid'
import LayoutSpace from '#/components/LayoutSpace'
import Auth from '#/components/Security/Login'

export const metadata = {
  title: '商品-智慧商城',
  description: 'Generated by create next app',
}

const ProductList: FC = Auth(
  {
    login: true,
  },
  () => {
    return (
      <>
        <ActionBar />

        <LayoutSpace direction={'vertical'} />

        <ProductGrid />
      </>
    )
  },
)

export default ProductList
