import { ReduxProvider } from '#/redux/provider'
// import { Inter } from 'next/font/google'
import { NextIntlClientProvider, useLocale } from 'next-intl'
import { notFound } from 'next/navigation'
import { AntdProvider } from './AntdProvider'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: { children: React.ReactNode; params: any }) {
  let messages
  try {
    // 适配客户端组件的
    messages = (await import(`../../messages/${props.params.locale}.json`)).default
  } catch (error) {
    notFound()
  }

  return (
    <NextIntlClientProvider
      locale={props.params.locale}
      messages={messages}
    >
      <html lang={props.params.locale}>
        <body style={{ margin: 0, backgroundColor: 'hsla(0,0%,0%,.9)' }}>
          <ReduxProvider>
            <AntdProvider>{props.children}</AntdProvider>
          </ReduxProvider>
        </body>
      </html>
    </NextIntlClientProvider>
  )
}
